name: project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - jupyter
  - numpy=1.23.5
  - pandas=1.5.2
  - scikit-learn=0.24.2
  - blas=*=mkl
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates
  - certifi
  - et_xmlfile=1.1.0
  - intel-openmp=2021.4.0
  - libffi=3.4.2
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - openpyxl=3.0.10
  - openssl
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pytz=2022.7
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - xz
  - zlib
  - packaging=21.3
  - backcall=0.2.0
  - decorator=5.1.1
  - ipython
  - pickleshare=0.7.5
  - prompt_toolkit=3.0.20
  - pygments=2.11.2
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - pip  # pipでしかインストールできないもの
  #   - some-pip-package==1.0.0 # pipで構築するとき
